# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d68a0c894ecbfb3fb09dc9e69d26ef5e26be5490968f1a93838cec8fb74e195ca2d473f586392f0ce41e571ed4231973f291b85198e341bf54d7d98b320306e

test:
  secret_key_base: d2826a5c881f80fe7a5469a63de8786d454adcdfc8a683acfeddbf77eaa392883a0f8d644f42d37583cfe5a2ab2af899e2a4ab1e4aabac9903220e7faf4b6c88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
